#!/bin/bash

DATA="__dump_file"
ERR="ERROR"
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

if [ ! -f "$DATA" ]; then
	echo -e "No testfiles to analyze"
	exit 0
fi

if [ "$(grep -c $ERR $DATA)" -ge 1 ]; then
	echo -e "==============================================="
	echo -e "Tests failed with the following errors"
	echo -e "${RED}`cat $DATA`${NC}"
	rm $DATA
	exit 1
fi

# cleanup
echo -e
echo -e "===================Test Log==================="
echo -e
echo -e "${GREEN}`cat $DATA`${NC}"
echo -e

rm $DATA

echo -e "${GREEN}All tests compleated successfully${NC}"
echo -e
exit 0
